#!/usr/bin/env bash

if [[ ! $UID = 0 ]]; then
    echo "Please run as root."
    exit 1
fi

clone_url=https://github.com/hayao-serene/serene-startdash.git
tmp_dir=/tmp/serene-startdash

set -eu

if [[ -d $tmp_dir ]]; then
    rm -rf $tmp_dir
fi

mkdir -p $tmp_dir
git clone $clone_url $tmp_dir
cd $tmp_dir
rm README.md
rm LICENSE.md
rm -rf .git
cd ..
dpkg -b $tmp_dir
pkg=$(find ./ -name "serene-startdash*.deb")